#!/bin/bash
# This file is @generated by <https://github.com/liblaf/copier-python>.
# DO NOT EDIT!
set -o errexit
set -o nounset
set -o pipefail

CODE="\
# tangerine-start: lazy-loader.py.jinja
import lazy_loader as lazy

__getattr__, __dir__, __all__ = lazy.attach_stub(__name__, __file__)
# tangerine-end
"

git_root=$(git rev-parse --show-toplevel)
find "$git_root/src/" -name '__init__.pyi' -type f -print0 |
  while IFS= read -d '' -r file; do
    file="${file%'i'}"
    if [[ ! -f $file ]]; then
      echo -n "$CODE" | tangerine > "$file"
    else
      tangerine "$file"
    fi
  done
