name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
