name: Release

on:
  push:
    branches-ignore:
      - assets**
      - gh-pages
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Packages
        uses: liblaf/actions-ts/install@dist
        with:
          brew: openssl@3
      - name: Setup mise
        uses: jdx/mise-action@v2
      - name: Build
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --bins --release --locked
      - name: Distribute
        run: mise run dist --name tangerine --target '${{ matrix.platform.target }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.platform.target }}
          path: dist/*
    strategy:
      matrix:
        platform:
          - runner: macos-latest
            target: aarch64-apple-darwin
          - runner: macos-latest
            target: x86_64-apple-darwin
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
      fail-fast: false
